@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Mar 02 03:24:26 -0500 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto fb63ba7dc9c14f489e6ed182b304a55b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot AEStb_behav xil_defaultlib.AEStb -log elaborate.log"
call xelab  -wto fb63ba7dc9c14f489e6ed182b304a55b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot AEStb_behav xil_defaultlib.AEStb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
