#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : base.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Dec 29 01:33:44 -0500 2019
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: base.sh [-help]
# usage: base.sh [-lib_map_path]
# usage: base.sh [-noclean_files]
# usage: base.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm lib_pkg_v1_0_2 fifo_generator_v13_2_4 lib_fifo_v1_0_13 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_21 axi_sg_v4_1_12 axi_dma_v7_1_20 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_19 axis_switch_v1_1_19 axi_infrastructure_v1_1_0 axi_vip_v1_1_5 processing_system7_vip_v1_0_7 proc_sys_reset_v5_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_19 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 axi_protocol_converter_v2_1_19 axi_clock_converter_v2_1_18 blk_mem_gen_v8_4_3 axi_dwidth_converter_v2_1_19 axi_mmu_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/ISE_Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/ISE_Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/4dac/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_21 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/e644/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_12 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/91f3/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_20 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/260a/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_dma_0_0/sim/base_axi_dma_0_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_axi_dma_1_0/sim/base_axi_dma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/635c/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_switch_v1_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/ac53/hdl/axis_switch_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axis_switch_0_0/sim/base_axis_switch_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/8c62/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_ps7_0/sim/base_ps7_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../../base/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_rst_ps7_100M_0/sim/base_rst_ps7_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/AXI_DMA_MASTER.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/AXI_DMA_SLAVE.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10_mac_mula3i2.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10_mul_32s_6jw.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10_mul_32s_bkb.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10_mul_32s_bXr.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10_mul_32s_cud.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10_mul_mul_2iS.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10_urem_7ns1iI.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/FC_1u_64u_10u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/FC_1u_64u_10u_s_AdQK.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/FC_1u_64u_10u_s_BdRK.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/FC_1u_1024u_64u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/fifo_w32_d2_A.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/fifo_w32_d50_A.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/pool_2u_32u_16u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/pool_2u_32u_16u_sbVr.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/pool_2u_32u_32u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/pool_2u_32u_32u_s4jc.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/pool_2u_32u_32u_s5jm.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/pool_2u_64u_8u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/pool_2u_64u_8u_s_cNA.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SCIG.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SCIG_1.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SCIG_2.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SCIG_2_inputBuf_V.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SCIG_inElem_V.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SCIG_inputBuf_V.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_75u_32u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_75u_32u_s_dEe.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_75u_32u_s_eOg.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_800u_32u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_800u_32u_s7jG.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_800u_32u_s8jQ.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_800u_64u_s.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/SMM_1u_800u_64u_sbZs.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_AXI_DMAeuR.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_FC_1u_1esQ.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_FC_1u_6etR.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_pool_2uenQ.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_pool_2uepQ.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_pool_2uerQ.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_SCIG_1_U0.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_SCIG_2_U0.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_SCIG_U0.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_SMM_1u_emP.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_SMM_1u_eoQ.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/start_for_SMM_1u_eqQ.v" \
    "$ref_dir/../../../../../base/ipshared/2e58/hdl/verilog/cifar_10.v" \
    "$ref_dir/../../../bd/base/ip/base_cifar_10_0_0/sim/base_cifar_10_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_xbar_0/sim/base_xbar_0.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_1/sim/base_xbar_1.v" \
    "$ref_dir/../../../../../base/ipshared/838b/hdl/verilog/simple_sum.v" \
    "$ref_dir/../../../bd/base/ip/base_simple_sum_0_1/sim/base_simple_sum_0_1.v" \
    "$ref_dir/../../../../../base/ipshared/a565/hdl/verilog/stream_mult.v" \
    "$ref_dir/../../../../../base/ipshared/a565/hdl/verilog/stream_mult_mul_32s_32s_32_6.v" \
    "$ref_dir/../../../bd/base/ip/base_stream_mult_0_1/sim/base_stream_mult_0_1.v" \
    "$ref_dir/../../../../../base/ipshared/dc6c/hdl/verilog/mult_constant.v" \
    "$ref_dir/../../../../../base/ipshared/dc6c/hdl/verilog/mult_constant_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../../base/ipshared/dc6c/hdl/verilog/mult_constant_mul_32s_32s_32_6.v" \
    "$ref_dir/../../../bd/base/ip/base_mult_constant_0_1/sim/base_mult_constant_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/ac9d/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/c001/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/e578/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_auto_us_0/sim/base_auto_us_0.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_us_1/sim/base_auto_us_1.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_us_2/sim/base_auto_us_2.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_us_3/sim/base_auto_us_3.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_0/sim/base_auto_pc_0.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_1/sim/base_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_mmu_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../../base/ipshared/b5b8/hdl/axi_mmu_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../base/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../../base/ip/base_ps7_0" +incdir+"C:/ISE_Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_s00_mmu_0/sim/base_s00_mmu_0.v" \
    "$ref_dir/../../../bd/base/sim/base.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base xil_defaultlib.glbl -o base_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc base_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
